version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: lucas123
      POSTGRES_DB: lucasDatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
