version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: lucas123
      POSTGRES_DB: lucasDatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: nest-api-container
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: lucas
      DATABASE_PASSWORD: lucas123
      DATABASE_NAME: lucasDatabase
    command: npm run start:prod

volumes:
  pgdata:
